# Generated by Django 5.0.7 on 2024-08-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_achievement_developer_discount_event_game_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='founded_date',
        ),
        migrations.AddField(
            model_name='developer',
            name='founded_year',
            field=models.IntegerField(default=2000),
        ),
    ]
