# Generated by Django 5.0.7 on 2024-08-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_developer_founded_date_developer_founded_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.CharField(default='https://i.ytimg.com/vi/Cr5rQ1NZ0Tw/maxresdefault.jpg', max_length=200),
        ),
    ]
