# Generated by Django 5.0.7 on 2024-08-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.CharField(default='https://store.steampowered.com/', max_length=100),
        ),
    ]
